### Create new report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Mercedes",
  "model": "GLC 300",
  "year": 2010,
  "mileage": 100000,
  "lng": 0,
  "lat": 0,
  "price": 30000
}

### Approve report
PATCH http://localhost:3000/reports/7
Content-Type: application/json

{
  "approved": true
}

### Get an estimate for the existing car
GET http://localhost:3000/reports?make=Mercedes&model=GLC300&year=2010&mileage=100000&lng=0&lat=0
