### Create new report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Ford",
  "model": "Mustang",
  "year": 2013,
  "mileage": 120500,
  "lng": 42,
  "lat": 47,
  "price": 50000
}

### Approve report
PATCH http://localhost:3000/reports/7
Content-Type: application/json

{
  "approved": true
}

### Get an estimate for the existing car
GET http://localhost:3000/reports?make=Ford&model=Mustang&year=2010&mileage=120000&lng=45&lat=44
